version: '2.1'

services:

  facade:
    build:
      context: ../facade
    image: facade:latest
    env_file:
      - facade.env
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: curl -f 0:8000/facade/index/
      interval: 10s
      timeout: 5s
      retries: 100000

  dashboard:
    build:
      context: ../dashboard
    image: dashboard:latest
    env_file:
      - dashboard.env
    depends_on:
      facade:
        condition: service_healthy
    ports:
      - '9000:9000'

  postgres:
    image: "postgres:alpine"
    env_file:
      - postgres.env
    healthcheck:
      test: psql -U postgres -d weather -c "select 1;"
      interval: 10s
      timeout: 5s
      retries: 10

  nginx:
    image: "nginx:stable-alpine"
    ports:
      - '8080:8080'
    volumes:
      - ../facade/facade/static/facade/:/var/www/static/facade
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      facade:
        condition: service_healthy
      dashboard:
        condition: service_started
