version: '2.1'

services:

  posts:
    build:
      context: .
    image: posts:latest
    env_file:
      - vars.env
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: curl -f 0:8000
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - '8000:8000'

  postgres:
    image: "postgres:alpine"
    env_file:
      - postgres.env
    healthcheck:
      test: psql -U postgres -d posts -c "select 1;"
      interval: 10s
      timeout: 5s
      retries: 10
